apiVersion: apps/v1
kind: Deployment
metadata:
  name: er-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: er
      tier: backend
  template:
    metadata:
      labels:
        app: er
        tier: backend
    spec:
      volumes:
        - name: application-properties
          configMap:
            name: er-backend-config
      containers:
        - name: er-backend-pod
          image: daisukezr/erdiagram-simplified-backend:latest@sha256:967b4109313f2631b3639f280e55aec7ec7dfb99a53be50c477dafc8cd78f7e9
          volumeMounts:
            - name: application-properties
              mountPath: /root/deployment/config/

