apiVersion: apps/v1
kind: Deployment
metadata:
  name: er-backend-deploy
spec:
  replcias: 2
  selector:
    matchLabels:
      app: er
      tier: backend
  template:
    metadata:
      labels:
        app: er
        tier: backend
    spec:
      containers:
        - name: er-backend-pod
          image: daisukezr/erdiagram-simplified-backend:latest

