apiVersion: apps/v1
kind: Deployment
metadata:
  name: er-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: er
      tier: backend
  template:
    metadata:
      labels:
        app: er
        tier: backend
    spec:
      volumes:
        - name: application-properties
          configMap:
            name: er-backend-config
      containers:
        - name: er-backend-pod
          image: daisukezr/erdiagram-simplified-backend:latest@sha256:4370cf366ab06b5f12f078d9a02dcf552ce1cbbeaba1bce04e6014c4352d6359
          volumeMounts:
            - name: application-properties
              mountPath: /root/deployment/config/

