apiVersion: v1
kind: PersistentVolume
metadata:
  name: er-tls-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv/er-tls"