apiVersion: v1
kind: PersistentVolume
metadata:
  name: er-tls-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #path: "/home/ec2-user/volume"
    path: /mnt/pv/er-tls
