apiVersion: apps/v1
kind: Deployment
metadata:
  name: er-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: er
      tier: backend
  template:
    metadata:
      labels:
        app: er
        tier: backend
    spec:
      volumes:
        - name: application-properties
          configMap:
            name: er-backend-config
      containers:
        - name: er-backend-pod
          image: daisukezr/erdiagram-simplified-backend:latest@sha256:ddf3c85e3c0db8090697d4b44574b38c52183aa38a0d1d0c0935e45b956f4ce7
          volumeMounts:
            - name: application-properties
              mountPath: /root/deployment/config/

