apiVersion: apps/v1
kind: Deployment
metadata:
  name: er-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: er
      tier: backend
  template:
    metadata:
      labels:
        app: er
        tier: backend
    spec:
      volumes:
        - name: application-properties
          configMap:
            name: er-backend-config
      containers:
        - name: er-backend-pod
          image: daisukezr/erdiagram-simplified-backend:latest@sha256:15bf4a6554b13a7b379567f47e40683e14e0f7bd4cd4317ce3a23e1a20fa330c
          volumeMounts:
            - name: application-properties
              mountPath: /root/deployment/config/

