name: Docker Image frontend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add Properties
      run: | 
        echo MONGODB_URI=${{ secrets.MONGODB_URI }} > ${{ github.workspace }}/frontend/.env &&
        echo NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} >> ${{ github.workspace }}/frontend/.env &&
        echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} > ${{ github.workspace }}/frontend/.env.production &&
        echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> ${{ github.workspace }}/frontend/.env.production &&
        echo FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }} >> ${{ github.workspace }}/frontend/.env.production &&
        echo FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }} >> ${{ github.workspace }}/frontend/.env.production &&
        echo GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }} >> ${{ github.workspace }}/frontend/.env.production &&
        echo GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }} >> ${{ github.workspace }}/frontend/.env.production &&
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> ${{ github.workspace }}/frontend/.env.production &&
        echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> ${{ github.workspace }}/frontend/.env.production
      
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: frontend/
        file: frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/erdiagram-simplified-frontend:latest